apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name:  {{ include "simple-consumer.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  prefix: /
  service: {{ include "simple-consumer.fullname" . }}:8080
