apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name:  {{ include "simple-consumer.fullname" . }}
spec:
  prefix: {{ .Values.ambassador.branchBase }}
  service: {{ include "simple-consumer.fullname" . }}:8080
